# Generated by Django 5.2.1 on 2025-05-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_links',
            name='category',
            field=models.CharField(default='vrijwilligers', max_length=255),
            preserve_default=False,
        ),
    ]
