# Generated by Django 5.2.1 on 2025-06-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_survey_links_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_links',
            name='year',
        ),
    ]
